import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#f0f2f7',
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: '#e0e4ec',
    borderRadius: 3,
    marginBottom: 10,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: 6,
    backgroundColor: '#4a6fa5',
    borderRadius: 3,
  },
  progress: {
    textAlign: 'center',
    fontSize: 13,
    color: '#888',
    marginBottom: 24,
    fontWeight: '600',
  },
  questionCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 28,
    marginBottom: 28,
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 5,
  },
  questionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#4a6fa5',
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  questionText: {
    fontSize: 21,
    fontWeight: '700',
    textAlign: 'center',
    color: '#2c3e50',
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 18,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#e0e4ec',
  },
  optionLetterBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#eef3f8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  optionLetterText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4a6fa5',
  },
  optionLetterBadgeCorrect: {
    backgroundColor: '#27ae60',
  },
  optionLetterBadgeIncorrect: {
    backgroundColor: '#e74c3c',
  },
  optionLetterTextSelected: {
    color: '#fff',
  },
  optionCorrect: {
    backgroundColor: '#e8f8ee',
    borderColor: '#27ae60',
  },
  optionIncorrect: {
    backgroundColor: '#fdecea',
    borderColor: '#e74c3c',
  },
  optionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2c3e50',
  },
  optionTextCorrect: {
    color: '#1e7e42',
  },
  optionTextIncorrect: {
    color: '#c0392b',
  },
  feedbackText: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 16,
  },
  feedbackCorrect: {
    color: '#27ae60',
  },
  feedbackIncorrect: {
    color: '#e74c3c',
  },
  nextButton: {
    backgroundColor: '#4a6fa5',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#4a6fa5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  scoreTracker: {
    textAlign: 'center',
    marginTop: 16,
    fontSize: 14,
    color: '#555',
    fontWeight: '600',
  },
  inputBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#e0e4ec',
  },
  inputBoxCorrect: {
    borderColor: '#27ae60',
    backgroundColor: '#e8f8ee',
  },
  inputBoxIncorrect: {
    borderColor: '#e74c3c',
    backgroundColor: '#fdecea',
  },
  submitButton: {
    backgroundColor: '#6c9a8b',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#6c9a8b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    backgroundColor: '#c7ced9',
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});